version: '3.7'

services:
  workouts:
    build: .
    command: python /manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/WorkoutAPI/
    ports:
      - 8000:8000
    env_file:
      - ./server/.env