version: '3.7'

services:
  workouts:
    build: .
    command: python /manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/WorkoutAPI/
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on: 
      - workouts-db
  workouts-db:
    image: postgres:12-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=workout
      - POSTGRES_PASSWORD=workout
      - POSTGRES_DB=workouts_dev
volumes:
  postgres_data: