# Generated by Django 3.0.8 on 2020-07-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
