# Generated by Django 3.0.8 on 2020-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200705_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='total_time',
            field=models.DurationField(),
        ),
    ]
